### ISSUE TITLE
need a new release for pygit2 1.4.0

### ISSUE THREAD

**Issue by chenrui333** [bennorth/literate-git#5]
👋  during libgit2 1.1.0 [upgrade PR](https://github.com/Homebrew/homebrew-core/pull/65706), we found that the new release is needed for literate-git, relevant error log

```
  In file included from src/blob.c:30:
  In file included from src/blob.h:34:
  src/types.h:36:2: error: You need a compatible libgit2 version (0.99.x or 1.0.x)
  #error You need a compatible libgit2 version (0.99.x or 1.0.x)
   ^
  1 error generated.
  error: command '/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang' failed with exit code 1
  Building wheel for pygit2 (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for pygit2
Failed to build pygit2
ERROR: Could not build wheels for pygit2 which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/literate-git/0.3.1_5/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/literate-git/0.3.1_5/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/literate-git/0.3.1_5/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 364, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for pygit2 which use PEP 517 and cannot be installed directly
Removed build tracker: '/private/tmp/pip-req-tracker-__xsh2z8'
```

---

also attach some relevant python_version requirements

```
pygit2<=0.28.2; python_version < '3.8'
pygit2>=1.2.0; python_version >= '3.8'
```

**Comment by bennorth** [comment]
I've just pushed changes to `develop` (967caf47f2f16) which move to `pygit2>=1.4.0`, so I'm closing this.  Please re-open if this doesn't address your use-case with Homebrew.  Thanks for the report.
